### ISSUE TITLE
Rename TransferFnWithState to something like PlasticTransferFn

### ISSUE THREAD

**Issue by jlstevens** [ioam/imagen#43]
This issue was originally a comment [here](https://github.com/ioam/topographica/blob/47463e971c97417018e85740b4f848a6051129b5/topo/transferfn/__init__.py#L227) in Topographica before ``TransferFnWithState`` was moved to ImaGen.

I'm not entirely sure this is an appropriate comment anyway as plasticity is not that meaningful in an Imagen context anyway - I am happy with ``TransferFnWithState`` and if you are too, then we should close this issue.

**Comment by jbednar** [comment]
That's the easiest way out, and I have no objection.
