### ISSUE TITLE
GaussianRandom needs a parameter for the variance

### ISSUE THREAD

**Issue by jlstevens** [ioam/imagen#45]
What is the point of a Gaussian distribution is I can't change the standard deviation or variance?!? 

Here is the current definition:

```python
class GaussianRandom(RandomGenerator):
    scale  = param.Number(default=0.25,softbounds=(0.0,2.0))
    offset = param.Number(default=0.50,softbounds=(-2.0,2.0))

    def _distrib(self,shape,p):
        return p.offset+p.scale*p.random_generator.standard_normal(shape)
```

Why would you do this when you can make something useful?

```python
class GaussianRandom(RandomGenerator):

    standard_deviation = param.Number(default=1, softbounds=(0,None))
    scale  = param.Number(default=0.25,softbounds=(0.0,2.0))
    offset = param.Number(default=0.50,softbounds=(-2.0,2.0))

    def _distrib(self,shape,p):
        return p.offset+p.scale*p.random_generator.normal(scale=p.standard_deviation,
                                                          size=shape)
```

That wasn't so hard now, was it? I can't fathom the logic behind the original implementation; maybe someone deliberately went out of their way to come up with  an annoying and useless? Who the hell uses ``standard_normal`` when ``normal`` is more general and actually useful?!

Anyway, I am happy to commit the sane version to master except that I am now worried about breaking backward compatibility. I suppose I need to see whether ``.standard_normal`` behaves like  ``,normal`` with unit standard deviation.

**Comment by jbednar** [comment]
Unless I'm missing something fundamental, there's no need for a ``standard_deviation`` parameter, if we already have a ``scale`` parameter.  Doesn't multiplying a zero-mean Gaussian by a scalar change its variance?  The ``scale`` and ``offset`` parameters are shared by all PatternGenerators, and so those are the right parameter names to use for any pattern for which they are meaningful, including this one.  You may want to add a note to the docstring explaining this, though.

**Comment by jlstevens** [comment]
Multiplying the output array by a scalar won't change the variance/standard deviation of the distribution. The fact that ``random_generator.normal`` takes a scale argument is confusing but I am fairly sure this is an entirely separate thing from the ``scale`` parameter of pattern generators (unless I have managed to get very confused myself!)

**Comment by jbednar** [comment]
I think you're right.  I was thinking about how, for a Gaussian function, if you multiply the x value you evaluate by a constant, it's the same as changing the variance.  But here the PG's scale is applied to the result, not the input, so it only changes the height.  (Plus this isn't a Gaussian function that even takes an input, so that type of input scaling won't even work here, since it's a probability distribution.)  So I'm ok with adding the standard_deviation parameter, in a backwards-compatible way.  And yes, the fact that normal() calls that parameter ``scale`` is very confusing, because it's hard to see in what way it's a scale from a user perspective; maybe that's why the parameter was omitted initially. But I do request that you be nicer when you post issues!

**Comment by jlstevens** [comment]
I am now completely confused and I am no longer sure what to do.

**Comment by jbednar** [comment]
I think your proposed change is good; just check that it doesn't change the results!  We probably aren't using it in .ty files or test cases, so please verify the change on a couple of test cases first.

**Comment by jlstevens** [comment]
That's right..I remember now!

If you have an offset such that the output is mostly positive, multiplying by a scalar isn't the same as increasing the spread. The only case when the scale parameter **does** match the standard deviation is when the distribution has zero mean.

As you noticed, I was a rather grumpy when filing this issue having just seen all the code in ImaGen that I really want to improve but can't fix.

**Comment by jbednar** [comment]
Ok, I think we've both gotten ourselves confused at different points -- e.g. I didn't see your edits to your earlier comment when I replied.  I'll close the issue now as being not needed, by my initial reasoning.

**Comment by jlstevens** [comment]
Right. I now agree that it does work because scale is applied *before* offset. 

That said, the fact that the scale matches the standard deviation (but not the variance!) is pretty far from evident, mainly because there is no useful documentation given with the scale parameter.

**Comment by jbednar** [comment]
Ok, I've deleted the crazy comments we were making in the middle there, leaving only the bits that make sense, to avoid spreading confusion. :-)  But yes, it does need a better docstring, probably for the scale parameter itself.
